# -*- coding: utf-8 -*-
"""matthew.thwaites (Oct 31, 2025, 2:30:43 PM)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/bigtimestudios/locations/us-central1/repositories/9702377e-4bcc-4968-880b-2f6133da8c7f
"""

from google.cloud import bigquery
import pandas as pd
from datetime import date, timedelta
import vertexai
from vertexai.generative_models import GenerativeModel
from google.auth import default
import numpy as np
import json

try:
    import vertexai
    from vertexai.generative_models import GenerativeModel
    VERTEX_AVAILABLE = True
except Exception:
    VERTEX_AVAILABLE = False

# set credentials
PROJECT_ID = "bigtimestudios"
LOCATION = "us-central1"
credentials, project = default()
client = bigquery.Client(credentials=credentials, project=project)
vertexai.init(project=PROJECT_ID, location=LOCATION)
model = GenerativeModel("gemini-2.5-pro")

# run dates
RUN_DATE = date.today()
RUN_DATE_STR = RUN_DATE.strftime("%Y-%m-%d")
YESTERDAY = (RUN_DATE - timedelta(days=1)).strftime("%Y-%m-%d")
WEEK_AGO  = (RUN_DATE - timedelta(days=7)).strftime("%Y-%m-%d")
TWO_WEEKS = (RUN_DATE - timedelta(days=14)).strftime("%Y-%m-%d")  # for 7d avg baseline

RUN_DATE_d = pd.to_datetime(RUN_DATE).date()
YESTERDAY_d = pd.to_datetime(YESTERDAY).date()
WEEK_AGO_d  = pd.to_datetime(WEEK_AGO).date()
TWO_WEEKS_d = pd.to_datetime(TWO_WEEKS).date()

###################
## get bq tables
###################

# DAU
df_dau = client.query('''
select
checkpoint Date,
DAU,
hours_played,
avg_time_per_player
from bigtimestudios.BT_ML.ai_bot_input_dau
''').to_dataframe()

df_dau.head()

# dungeons
df_dungeon = client.query('''
select
*
from bigtimestudios.BT_ML.ai_bot_input_dungeon
''').to_dataframe()

df_dungeon.head()

# revenue
df_revenue = client.query('''
select
*
from bigtimestudios.BT_ML.ai_bot_input_revenue
''').to_dataframe()

# tokens
df_tokens = client.query('''
select
*
from bigtimestudios.BT_ML.ai_bot_input_token
''').to_dataframe()

df_crafts = client.query('''
select
*
from bigtimestudios.BT_ML.ai_bot_input_crafts
''').to_dataframe()

# help function
def pct(a,b):
  if b in (0, None, np.nan) or pd.isna(b):
    return np.nan
  return (a-b)/b

# Revenue deltas
rev_today = df_revenue[df_revenue['Date'] == RUN_DATE_STR].copy()
rev_yday  = df_revenue[df_revenue['Date'] == YESTERDAY].copy()
rev_7d    = df_revenue[(df_revenue['Date'] < RUN_DATE) & (df_revenue['Date'] >= WEEK_AGO_d)].copy()

# today metrics
total_rev_today = rev_today['Revenue'].sum() if not rev_today.empty else 0
buyers_today  = rev_today['Buyers'].sum() if not rev_today.empty else 0
tx_today = rev_today['transactions'].sum() if not rev_today.empty else 0

# yesterday metrics
total_rev_yday = rev_yday['revenue'].sum() if not rev_yday.empty else 0
rev_7d_avg = rev_7d['revenue'].sum()/7 if not rev_7d.empty else 0

rev_dod = pct(total_rev_today, total_rev_yday)
rev_vs7 = pct(total_rev_today, rev_7d_avg)

# DAU deltas
df_dau['Date'] = pd.to_datetime(df_dau['Date'])

dau_today = df_dau[df_dau['Date'] == RUN_DATE_STR].copy()
dau_yday  = df_dau[df_dau['Date'] == YESTERDAY].copy()
dau_7d    = df_dau[(df_dau['Date'] < RUN_DATE_STR) & (df_dau['Date'] >= WEEK_AGO)].copy()

dau_today_v = int(dau_today['DAU'].sum()) if not dau_today.empty else 0
dau_yday_v  = int(dau_yday['DAU'].sum()) if not dau_yday.empty else np.nan
dau_7d_avg  = float(dau_7d['DAU'].mean()) if not dau_7d.empty else np.nan

dau_dod = pct(dau_today_v, dau_yday_v)
dau_vs7 = pct(dau_today_v, dau_7d_avg)

# gameplay data
df_dungeon['Day'] = pd.to_datetime(df_dungeon['Day'])
gp_today = df_dungeon[df_dungeon['Day'] == RUN_DATE_STR].copy()
gp_yday  = df_dungeon[df_dungeon['Day'] == YESTERDAY].copy()

# function
def top_change(current, prior, key_cols, metric):
  if current.empty:
    return pd.DataFrame(columns=key_cols + [metric + 'delta'])
  c = current[key_cols + [metric]].groupby(key_cols, as_index=False).sum()
  p = prior[key_cols + [metric]].groupby(key_cols, as_index=False).sum() if not prior.empty else pd.DataFrame(columns=key_cols + [metric])
  merged = c.merge(p, on=key_cols, how='left', suffixes=('','_yday'))
  merged['delta'] = merged[metric] - metric[f"{metric}_yday"].fillna(0)
  merged = merged.sort_values('delta', ascending=False)
  return merged

# gameplay changes
gp_players_chg = top_change(gp_today, gp_yday, ['dungeon_type','mission'], 'players').head(10)
gp_sand_chg   = top_change(gp_today, gp_yday, ['dungeon_type', 'mission'], 'sand_consumed').head(10)
gp_bt_chg = top_change(gp_today, gp_yday, ['dungeon_type', 'mission'], 'bigtime_consumed').head(10)

# token drops
df_tokens['Day'] = pd.to_datetime(df_tokens['Day'])
tok_today = df_tokens[df_tokens['Day']==RUN_DATE_d].copy()
tok_yday  = df_tokens[df_tokens['Day']==YESTERDAY_d].copy()

tok_amt_chg   = top_change(tok_today, tok_yday, ['action_type', 'source_string', 'dungeon_location'], 'total_amount').head(15)
tok_users_chg = top_change(tok_today, tok_yday, ['action_type', 'source_string', 'dungeon_location'], 'users').head(15)

# Crafting
cr_today = df_crafts[df_crafts['Day'] == RUN_DATE_STR].copy()
cr_yday  = df_crafts[df_crafts['Day'] == YESTERDAY].copy()

cr_crafts_chg = top_change(cr_today, cr_yday, ['item_name'], 'crafts').head(15)
cr_users_chg  = top_change(cr_today, cr_yday, ['item_name'], 'users').head(15)

summary_metrics = {
    "date": RUN_DATE_STR,
    "revenue": {
        "today": total_rev_today,
        "DoD_pct": None if pd.isna(rev_dod) else round(100*rev_dod, 2),
        "vs7d_avg_pct": None if pd.isna(rev_vs7) else round(100*rev_vs7, 2),
        "buyers": buyers_today,
        "transactions": tx_today,
    },
    "dau": {
        "today": dau_today_v,
        "DoD_pct": None if pd.isna(dau_dod) else round(100*dau_dod, 2),
        "vs7d_avg_pct": None if pd.isna(dau_vs7) else round(100*dau_vs7, 2),
        "avg_time_today_min": None if dau_today.empty else round(float(dau_today['avg_time_per_user'].mean()), 2)
    }
}

summary_metrics

print(json.dumps(summary_metrics, indent=2))
print("\nTop gameplay changes (players):");      display(gp_players_chg)
print("\nTop gameplay changes (sand):");         display(gp_sand_chg)
print("\nTop gameplay changes ($BIGTIME):");     display(gp_bt_chg)
print("\nToken changes (amount):");              display(tok_amt_chg)
print("\nToken changes (users):");               display(tok_users_chg)
print("\nCrafting changes (crafts):");           display(cr_crafts_chg)
print("\nCrafting changes (users):");            display(cr_users_chg)

# ----------------
# LLM context prep
# ----------------
def compact(df: pd.DataFrame, n=8):
    if df is None or df.empty:
        return "None"
    return df.head(n).to_markdown(index=False)

ctx = {
    "date": RUN_DATE_STR,
    "rev": summary_metrics["revenue"],
    "dau": summary_metrics["dau"],
    "gp_players": compact(gp_players_chg[['dungeon_type','mission','playersdelta']]),
    "gp_sand": compact(gp_sand_chg[['dungeon_type','mission','sand_consumeddelta']]),
    "gp_bigtime": compact(gp_bt_chg[['dungeon_type','mission','bigtime_consumeddelta']]),
    "tok_amount": compact(tok_amt_chg[['action_type','source_string','dungeon_location','total_amountdelta']]),
    "tok_users": compact(tok_users_chg[['action_type','source_string','dungeon_location','usersdelta']]),
    "craft_crafts": compact(cr_crafts_chg[['item_name','craftsdelta']]),
    "craft_users": compact(cr_users_chg[['item_name','usersdelta']]),
}

print(json.dumps({"date": ctx["date"], "rev": ctx["rev"], "dau": ctx["dau"]}, indent=2))

# ----------------
# AI Summary (Gemini) with fallback
# ----------------
def format_prompt(ctx):
    return f'''
You are the Head of Analytics for the MMO 'Big Time'. Produce a blunt, executive daily update for **{ctx["date"]}**.
Only include what moved. Avoid fluff. Use bullets. Include % deltas when available.
Sections:
1) KPIs (Revenue, DAU)
2) Gameplay (dungeons/portals): top movers by players, sand, $BIGTIME consumption
3) Token Drops ($BIGTIME): biggest sources/sinks; notable dungeon-linked grants
4) Crafting: top crafted items & changes

KPI:
Revenue: {ctx["rev"]}
DAU: {ctx["dau"]}

Gameplay — Players (top):\n{ctx["gp_players"]}

Gameplay — Sand (top):\n{ctx["gp_sand"]}

Gameplay — $BIGTIME Consumed (top):\n{ctx["gp_bigtime"]}

Token — Amount (top):\n{ctx["tok_amount"]}

Token — Users (top):\n{ctx["tok_users"]}

Crafting — Crafts (top):\n{ctx["craft_crafts"]}

Crafting — Users (top):\n{ctx["craft_users"]}
    '''.strip()

def summarize_with_vertex(prompt_text: str) -> str:
    return model.generate_content(prompt_text).text

prompt_text = format_prompt(ctx)
ai_summary = summarize_with_vertex(prompt_text)

if not ai_summary:
    # Fallback: rules-based summary
    lines = []
    lines.append(f"**Daily Update — {RUN_DATE_STR}**")
    # KPIs
    lines.append("• KPIs:")
    lines.append(
        f"  - Revenue: ${total_rev_today:,.0f} "
        f"({('N/A' if np.isnan(rev_dod) else f'{rev_dod*100:+.1f}% DoD')}, "
        f"{('N/A' if np.isnan(rev_vs7) else f'{rev_vs7*100:+.1f}% vs 7d avg')}); "
        f"buyers={buyers_today:,}, tx={tx_today:,}"
    )
    lines.append(
        f"  - DAU: {dau_today_v:,} "
        f"({('N/A' if np.isnan(dau_dod) else f'{dau_dod*100:+.1f}% DoD')}, "
        f"{('N/A' if np.isnan(dau_vs7) else f'{dau_vs7*100:+.1f}% vs 7d avg')})"
    )

    def bullets(df, label, cols):
        out = [f"• {label}:"]
        if df is None or df.empty:
            out.append("  - No material change.")
        else:
            for _, r in df.iterrows():
                vals = " | ".join([f"{c}={r[c]}" for c in cols if c in r])
                out.append(f"  - {vals}")
        return out

    # Gameplay
    lines += bullets(gp_players_chg.head(5), "Gameplay — Players ↑", ["dungeon_type","mission","players","delta"])
    lines += bullets(gp_sand_chg.head(5), "Gameplay — Sand ↑", ["dungeon_type","mission","sand_consumed","delta"])
    lines += bullets(gp_bt_chg.head(5), "Gameplay — $BIGTIME Consumed ↑", ["dungeon_type","mission","bigtime_consumed","delta"])
    # Token
    lines += bullets(tok_amt_chg.head(5), "Token — Amount ↑", ["action_type","source_string","dungeon_location","total_amount","delta"])
    lines += bullets(tok_users_chg.head(5), "Token — Users ↑", ["action_type","source_string","dungeon_location","users","delta"])
    # Crafting
    lines += bullets(cr_crafts_chg.head(5), "Crafting — Crafts ↑", ["item_name","crafts","delta"])
    lines += bullets(cr_users_chg.head(5), "Crafting — Users ↑", ["item_name","users","delta"])

    ai_summary = "\n".join(lines)

print("\n===== AI SUMMARY =====\n")
print(ai_summary[:4000])